# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonsighting',
            name='reported',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 15, 23, 53, 18, 326266, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonsighting',
            name='verification',
            field=models.CharField(choices=[('V_UNVERIFIED', 'Unverified')], default='V_UNVERIFIED', max_length=15),
        ),
    ]
